import type { TaskTrigger } from "../../../server/src/game/leagues/triggers/TriggerTypes";
import { LEAGUE_TASK_TRIGGER_BY_ID } from "./leagueTaskTriggers.data";

/**
 * Explicit MVP task triggers (generated by import-mvp-tasks.ts).
 */
export function getLeagueTaskTrigger(taskId: number): TaskTrigger | undefined {
    return LEAGUE_TASK_TRIGGER_BY_ID[taskId | 0];
}
